run_name: DQN_hangman
project_name: "hangman"
group_name: null
mode: "online" # "online" or "disabled" ("offline" too but not used)
device: "cuda:0"
load_checkpoint: False
checkpoint_path: null

# Environment
# SEEDS: [118398, 676190, 786456, 171936, 887739, 919409, 711872, 442081, 189061, 117840]
env:
  seed: 118398

# collector
# Total time steps corresponds to num_iterations * training_steps
# In other words, there are num_iterations cycles of training_steps steps each
# collector:
#   num_iterations: 200
#   training_steps: 10
#   frames_per_batch: 4 # update_period in Dopamine
#   epsilon_start: 1.0
#   epsilon_end: 0.01
#   epsilon_decay_period: 50_000 # TODO: decay has to init after warmup
#   init_random_frames: 0 # min_replay_history in Dopamine

collector:
  num_iterations: 20000
  training_steps: 1000
  frames_per_batch: 4 # update_period in Dopamine
  epsilon_start: 1.0
  epsilon_end: 0.01
  epsilon_decay_period: 250_000 # TODO: decay has to init after warmup
  init_random_frames: 20_004 # 10_004 # min_replay_history in Dopamine

# policy
policy:
  type: "BERTDQNPolicy"
  hidden_size: 128 #128 # 300 for using Glove embeddings
  num_hidden_layers: 2  # Change as needed
  num_attention_heads: 2
  max_position_embeddings: 512  # Max word length
  intermediate_size: 512 # Always 4 times hidden_size (rule of thumb)
  max_word_length: 32
  vocab_size: 30 # 26 letters + 4 special tokens
  # hidden_size: 768
  # num_hidden_layers: 12
  # num_attention_heads: 12
  # max_position_embeddings: 512
  # intermediate_size: 3072
  # max_word_length: 32
  # vocab_size: 30  # Or the appropriate vocab size
  load_pretrained_bert: true
  load_pretrained_bert_path: "models/bert_tiny.pth"

# buffer
buffer:
  buffer_size: 1_000_000
  batch_size: 512
  scratch_dir: null
  prioritized_replay: True
  alpha: 0.6
  beta: 0.4


# logger
logger:
  save_checkpoint: True
  save_checkpoint_freq: 50
  evaluation:
    enable: False
    eval_freq: 1000

# Optim
optim:
  lr: 0.0000625 # 0.0005,0.0001, 0.0000625
  max_grad_norm: 10
  eps: 1.5e-4 # default: 1e-08 # rainbow 1.5e-4

# loss
loss:
  double_dqn: True
  gamma: 0.99 #
  target_update_period: 2_000
